# ANN Regression Model 

Importing Libraries

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt 


# Part-1 Data Processing

Import Data set

In [17]:
data = pd.read_excel('Folds5x2_pp.xlsx')
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [19]:
data.head(10)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42
8  14.64  45.00  1021.78  41.25  475.98
9  11.74  43.56  1015.14  70.72  477.50

In [20]:
target_variable = ['PE']
predictors = ['AT', 'V', 'AP', 'RH']
x=data[predictors].values
y=data[target_variable].values

In [21]:
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [22]:
y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Quick sanity check with the shapes of Training and testing datasets
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(7654, 4)
(7654, 1)
(1914, 4)
(1914, 1)


# Part - 2 : Building the ANN

Intializing ANN

Lets quickly understand the hyperparameters in below code snippets

* units=6: This means we are creating a layer with five neurons in it. Each of these six neurons will be receiving the values of inputs, for example, the values of ‘AT’ will be passed to all six neurons, similarly all other columns.

* input_dim=4: This means there are seven predictors in the input data which is expected by the first layer. If you see the second dense layer, we don’t specify this value, because the Sequential model passes this information further to the next layers.

* kernel_initializer=’normal’: When the Neurons start their computation, some algorithm has to decide the value for each weight. This parameter specifies that. You can choose different values for it like ‘normal’ or ‘glorot_uniform’.

* activation=’relu’: This specifies the activation function for the calculations inside each neuron. You can choose values like ‘relu’, ‘tanh’, ‘sigmoid’, etc.

* batch_size=32: This specifies how many rows will be passed to the Network in one go after which the SSE calculation will begin and the neural network will start adjusting its weights based on the errors. When all the rows are passed in the batches of 32 rows each as specified in this parameter, then we call that 1-epoch. Or one full data cycle. This is also known as mini-batch gradient descent. A small value of batch_size will make the ANN look at the data slowly, like 2 rows at a time or 4 rows at a time which could lead to overfitting, as compared to a large value like 20 or 50 rows at a time, which will make the ANN look at the data fast which could lead to underfitting. Hence a proper value must be chosen using hyperparameter tuning.

* Epochs=100: The same activity of adjusting weights continues for 100 times, as specified by this parameter. In simple terms, the ANN looks at the full training data 100 times and adjusts its weights.

In [24]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6,input_dim=4, activation='relu'))

Adding the second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1))

# Part 3 - Training the ANN

Compiling the ANN

In [28]:
ann.compile(optimizer='adam', loss='mean_squared_error')

# Training the ANN model on the Training set

In [29]:
ann.fit(x_train,y_train, batch_size=32,validation_data=(x_test,y_test), epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 546us/step - loss: 1707.0836 - val_loss: 509.8993
Epoch 2/100
240/240 [==============================] - 0s 680us/step - loss: 478.1786 - val_loss: 449.1300
Epoch 3/100
240/240 [==============================] - 0s 367us/step - loss: 394.7352 - val_loss: 339.3232
Epoch 4/100
240/240 [==============================] - 0s 369us/step - loss: 281.0145 - val_loss: 222.1513
Epoch 5/100
240/240 [==============================] - 0s 380us/step - loss: 160.4613 - val_loss: 108.7930
Epoch 6/100
240/240 [==============================] - 0s 374us/step - loss: 85.8889 - val_loss: 63.6952
Epoch 7/100
240/240 [==============================] - 0s 378us/step - loss: 56.0397 - val_loss: 46.8736
Epoch 8/100
240/240 [==============================] - 0s 372us/step - loss: 43.3611 - val_loss: 39.2518
Epoch 9/100
240/240 [==============================] - 0s 380us/step - loss: 37.8348 - val_loss: 33.9546
Epoch 10/100
240/240 [======================

240/240 [==============================] - 0s 376us/step - loss: 27.2147 - val_loss: 22.0522
Epoch 79/100
240/240 [==============================] - 0s 376us/step - loss: 25.1167 - val_loss: 24.7362
Epoch 80/100
240/240 [==============================] - 0s 370us/step - loss: 25.1169 - val_loss: 27.0094
Epoch 81/100
240/240 [==============================] - 0s 370us/step - loss: 25.4688 - val_loss: 28.7553
Epoch 82/100
240/240 [==============================] - 0s 370us/step - loss: 25.8608 - val_loss: 22.1051
Epoch 83/100
240/240 [==============================] - 0s 373us/step - loss: 26.0499 - val_loss: 22.2846
Epoch 84/100
240/240 [==============================] - 0s 378us/step - loss: 26.2262 - val_loss: 24.6334
Epoch 85/100
240/240 [==============================] - 0s 409us/step - loss: 25.1829 - val_loss: 23.2906
Epoch 86/100
240/240 [==============================] - 0s 380us/step - loss: 25.0714 - val_loss: 22.6125
Epoch 87/100
240/240 [==============================] - 0s 

# Predicting the results of the Test set

In [15]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 282us/step
[[ 23.94 431.23]
 [ 23.94 460.01]
 [ 23.94 461.14]
 ...
 [ 23.94 473.26]
 [ 23.94 438.  ]
 [ 23.94 463.28]]
